import {
  RealtimeMessageType,
  ThreadEventSchema,
  ThreadEventSchemaType,
} from "@/app/schemas/realtime";
import { applyReactionDelta } from "@/lib/reactions";
import { orpc } from "@/lib/orpc";
import { useQueryClient } from "@tanstack/react-query";
import usePartySocket from "partysocket/react";
import { createContext, ReactNode, useContext, useMemo } from "react";

interface ThreadRealtimeProviderProps {
  children: ReactNode;
  threadId: string;
  currentUserId?: string;
}

type ThreadRealtimeContextValue = {
  send: (event: ThreadEventSchemaType) => void;
};

const ThreadRealtimeContext = createContext<null | ThreadRealtimeContextValue>(
  null,
);

export function ThreadRealtimeProvider({
  children,
  threadId,
  currentUserId,
}: ThreadRealtimeProviderProps) {
  const queryClient = useQueryClient();

  type ThreadListOptions = ReturnType<
    typeof orpc.message.thread.list.queryOptions
  >;

  type ThreadQueryData = Awaited<ReturnType<ThreadListOptions["queryFn"]>>;

  const socket = usePartySocket({
    host: process.env.NEXT_PUBLIC_WORKER_URL,
    room: `thread-${threadId}`,
    party: "chat",
    onMessage(e) {
      try {
        const parsed = JSON.parse(e.data);

        const result = ThreadEventSchema.safeParse(parsed);

        if (!result.success) {
          console.log("Invalid thread event");
          return;
        }

        const event = result.data;

        if (event.type === "thread:reply:created") {
          const replyObject = event.payload.reply as RealtimeMessageType;

          //Use the same key generated by orpc
          const listOptions = orpc.message.thread.list.queryOptions({
            input: { messageId: threadId },
          });

          queryClient.setQueryData<ThreadQueryData>(
            listOptions.queryKey,
            (old) => {
              if (!old) return old;

              const reply = {
                ...replyObject,
                reactions: Array.isArray(replyObject.reactions)
                  ? replyObject.reactions
                  : [],
              } as ThreadQueryData["messages"][number];

              return {
                ...old,
                messages: [...old.messages, reply],
              };
            },
          );

          return;
        }

        if (event.type === "thread:reaction:updated") {
          const {
            messageId,
            emoji,
            userId,
            added,
            threadId: tid,
          } = event.payload;

          if (tid !== threadId) {
            return;
          }

          //Use the same key generated by orpc
          const listOptions = orpc.message.thread.list.queryOptions({
            input: { messageId: threadId },
          });

          queryClient.setQueryData(listOptions.queryKey, (old) => {
            if (!old) return old;

            if (messageId === threadId) {
              return {
                ...old,
                parent: {
                  ...old.parent,
                  reactions: applyReactionDelta(
                    old.parent.reactions,
                    emoji,
                    userId,
                    added,
                    currentUserId,
                  ),
                },
              };
            }

            return {
              ...old,
              messages: old.messages.map((m) =>
                m.id === messageId
                  ? {
                      ...m,
                      reactions: applyReactionDelta(
                        m.reactions,
                        emoji,
                        userId,
                        added,
                        currentUserId,
                      ),
                    }
                  : m,
              ),
            };
          });

          return;
        }
      } catch (error) {
        console.log("Something went wrong", error);
      }
    },
  });

  const value = useMemo<ThreadRealtimeContextValue>(() => {
    return {
      send: (event) => {
        socket.send(JSON.stringify(event));
      },
    };
  }, [socket]);

  return (
    <ThreadRealtimeContext.Provider value={value}>
      {children}
    </ThreadRealtimeContext.Provider>
  );
}

export function useThreadRealtime(): ThreadRealtimeContextValue {
  const ctx = useContext(ThreadRealtimeContext);

  if (!ctx) {
    throw new Error(
      "useThreadRealtime must be used within a ThreadRealtimeProvider",
    );
  }
  return ctx;
}

export function useOptionalThreadRealtime(): ThreadRealtimeContextValue | null {
  return useContext(ThreadRealtimeContext);
}
